CC=gcc
CFLAGS=-fdiagnostics-color=always -g
TARGET=D:\00-workspace\02-studies\01-operating-systems\01-introductory-task\program.exe
SOURCES=main.c mylib.c

all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(TARGET)

clean:
	del $(TARGET)
